### ISSUE TITLE
Deploy "Coming soon" w/ DNS update

### ISSUE THREAD

**Issue by jackiekazil** [18F/myusa#583]
- [x] Create coming soon page - #582
- [x] Putting assets in S3 bucket - #611 
- [x] Get CloudFront and TLS setup - #612 (at 12pm-ish 04/20)
- [x] Confirm that coming soon page will initially only be on my.usa.gov and not myusa.gov - #613
- [x] Delegate DNS - #614 (at 12pm-ish 04/20)
- [x] Tell current MyUSA users before External DNS change - #615 (pinged @jgrevich in myusa channel)
- [x] Confirm final external DNS propagation -  #616 (right after 12pm-ish 04/20 -- this should take 24-48 hours)
- [x] Cut off CGI for my.usa.gov

**Comment by jackiekazil** [comment]
@adelevie, I am going to take this ticket and create sub tickets for the series of tasks.

**Comment by jackiekazil** [comment]
Ty for everyone who helped tackle this! -- @adelevie @yozlet @kategarklavs @NoahKunin @mkhandekar @dlapiduz  -- after trying to mention everyone, I am certain that I forgot someone. 

:100: :us: :muscle:

**Comment by adelevie** [comment]
Don't forget @juliaelman!

**Comment by jackiekazil** [comment]
Now, @juliaelman gets two mentions! :-)
