### ISSUE TITLE
Sign in flow — to code

### ISSUE THREAD

**Issue by mkhandekar** [18F/myusa#735]
**Background:**

In the previously handed off sign in flow, there were issues around header & footer consistency, and confusion about the initial sign in screen. Last week the team discussed progress on the sign in flow [on invision](https://invis.io/N83NTICPE). The following will be the canonical screens for the various ways visitors can sign into MyUSA and integrator websites. 

**Major changes / adjustments:**
* less text everywhere
* fewer more steps (the green 1, 2, 3’s)
* expanded background areas 
* subtle transitions within the design and between pages (desired effect is for the steps to feel less drastic / belaboured) 
* new headers when signing in from an integrator website (to clarify relationship between MyUSA and Integrator)
* google oauth is *not* present when signing in from MyUSA
* google oauth is *only* present when signing in from the integrator website, *if* integrator has requested it

**Issues bundled into this one:** 
- [ ] Sign in from MyUSA  
- [ ] Sign in from Integrator using Email  
- [ ] Sign in from Integrator using Google  
- [ ] Signed in: Permissions  
- [ ] [Header & Footer states](https://github.com/18F/myusa/issues/729)  
- [ ] [Integrators should be able to specify their app name](https://github.com/18F/myusa/issues/734)  
- [ ] [Collect and show integrator logos in sign in flow](https://github.com/18F/myusa/issues/733)  
- [ ] Integrators need a way to request Google as a sign in option

**Comment by jackiekazil** [comment]
This is a requirement for #751.
